create table "public"."careers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by" uuid not null,
    "contents" text not null
);


alter table "public"."careers" enable row level security;

CREATE UNIQUE INDEX careers_pkey ON public.careers USING btree (id);

alter table "public"."careers" add constraint "careers_pkey" PRIMARY KEY using index "careers_pkey";

alter table "public"."careers" add constraint "careers_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id) not valid;

alter table "public"."careers" validate constraint "careers_created_by_fkey";

grant delete on table "public"."careers" to "anon";

grant insert on table "public"."careers" to "anon";

grant references on table "public"."careers" to "anon";

grant select on table "public"."careers" to "anon";

grant trigger on table "public"."careers" to "anon";

grant truncate on table "public"."careers" to "anon";

grant update on table "public"."careers" to "anon";

grant delete on table "public"."careers" to "authenticated";

grant insert on table "public"."careers" to "authenticated";

grant references on table "public"."careers" to "authenticated";

grant select on table "public"."careers" to "authenticated";

grant trigger on table "public"."careers" to "authenticated";

grant truncate on table "public"."careers" to "authenticated";

grant update on table "public"."careers" to "authenticated";

grant delete on table "public"."careers" to "service_role";

grant insert on table "public"."careers" to "service_role";

grant references on table "public"."careers" to "service_role";

grant select on table "public"."careers" to "service_role";

grant trigger on table "public"."careers" to "service_role";

grant truncate on table "public"."careers" to "service_role";

grant update on table "public"."careers" to "service_role";


